DROP DATABASE IF EXISTS db_revoo;
CREATE DATABASE db_revoo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE db_revoo;

CREATE TABLE PERFIL (
  ID_PERFIL      INT AUTO_INCREMENT PRIMARY KEY,
  NOM_PERFIL     VARCHAR(60)  NOT NULL,
  DT_CRIACAO     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DT_ATUALIZACAO DATETIME     NULL,
  UNIQUE (NOM_PERFIL)
);

CREATE TABLE CATEGORIA_HABITO (
  ID_CATEGORIA_HABITO INT AUTO_INCREMENT PRIMARY KEY,
  NOM_CATEGORIA       VARCHAR(80)  NOT NULL,
  DES_CATEGORIA       VARCHAR(200),
  DT_CRIACAO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DT_ATUALIZACAO      DATETIME     NULL,
  UNIQUE (NOM_CATEGORIA)
);

CREATE TABLE USUARIO (
  ID_USUARIO      INT AUTO_INCREMENT PRIMARY KEY,
  NOM_USUARIO     VARCHAR(100) NOT NULL,
  EMAIL           VARCHAR(120) NOT NULL,
  SENHA_HASH      VARCHAR(200) NOT NULL,
  DT_NASC         DATE         NULL,
  DT_CRIACAO      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DT_ATUALIZACAO  DATETIME     NULL,
  UNIQUE (EMAIL)
);

CREATE TABLE COLABORADOR (
  ID_COLABORADOR  INT AUTO_INCREMENT PRIMARY KEY,
  ID_USUARIO      INT NOT NULL,
  MATRICULA       VARCHAR(30),
  CARGO           VARCHAR(60),
  SETOR           VARCHAR(60),
  DT_ADMISSAO     DATE,
  DT_DESLIGAMENTO DATE,
  DT_CRIACAO      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DT_ATUALIZACAO  DATETIME NULL,
  UNIQUE (ID_USUARIO),
  UNIQUE (MATRICULA),
  CONSTRAINT FK_COLAB_USUARIO
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE HABITO (
  ID_HABITO            INT AUTO_INCREMENT PRIMARY KEY,
  ID_CATEGORIA_HABITO  INT NOT NULL,
  NOM_HABITO           VARCHAR(120) NOT NULL,
  DES_HABITO           VARCHAR(400),
  QTD_SEMANAL_SUGERIDA DECIMAL(5,2),
  PONTOS_BASE          DECIMAL(8,2) DEFAULT 0,
  IND_ATIVO            CHAR(1)      DEFAULT 'S',
  DT_CRIACAO           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DT_ATUALIZACAO       DATETIME     NULL,
  UNIQUE (NOM_HABITO),
  CONSTRAINT FK_HABITO_CATEG
    FOREIGN KEY (ID_CATEGORIA_HABITO) REFERENCES CATEGORIA_HABITO(ID_CATEGORIA_HABITO)
);

CREATE TABLE META_SEMANAL (
  ID_META_SEMANAL      INT AUTO_INCREMENT PRIMARY KEY,
  ID_COLABORADOR       INT NOT NULL,
  ID_HABITO            INT NOT NULL,
  DT_SEMANA_INICIO     DATE NOT NULL,
  DT_SEMANA_FIM        DATE NOT NULL,
  QTD_META_SEMANAL     DECIMAL(8,2) NOT NULL,
  IND_STATUS           VARCHAR(20) DEFAULT 'ATIVA',
  DT_CRIACAO           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DT_ATUALIZACAO       DATETIME NULL,
  UNIQUE (ID_COLABORADOR, ID_HABITO, DT_SEMANA_INICIO),
  CONSTRAINT FK_META_COLAB
    FOREIGN KEY (ID_COLABORADOR) REFERENCES COLABORADOR(ID_COLABORADOR),
  CONSTRAINT FK_META_HABITO
    FOREIGN KEY (ID_HABITO) REFERENCES HABITO(ID_HABITO)
);

CREATE TABLE REGISTRO_PROGRESSO (
  ID_REGISTRO_PROGRESSO  INT AUTO_INCREMENT PRIMARY KEY,
  ID_META_SEMANAL        INT NOT NULL,
  DATA_REGISTRO          DATE NOT NULL,
  QTD_REALIZADA          DECIMAL(8,2) NOT NULL,
  OBS                    VARCHAR(400),
  DT_CRIACAO             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DT_ATUALIZACAO         DATETIME NULL,
  UNIQUE (ID_META_SEMANAL, DATA_REGISTRO),
  CONSTRAINT FK_REG_META
    FOREIGN KEY (ID_META_SEMANAL) REFERENCES META_SEMANAL(ID_META_SEMANAL)
);

CREATE TABLE USUARIO_PERFIL (
  ID_USUARIO_PERFIL  INT AUTO_INCREMENT PRIMARY KEY,
  ID_USUARIO         INT NOT NULL,
  ID_PERFIL          INT NOT NULL,
  DT_CRIACAO         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (ID_USUARIO, ID_PERFIL),
  CONSTRAINT FK_UP_USUARIO
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
  CONSTRAINT FK_UP_PERFIL
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID_PERFIL)
);

CREATE INDEX IX_COLAB_USUARIO      ON COLABORADOR (ID_USUARIO);
CREATE INDEX IX_HABITO_CATEG       ON HABITO (ID_CATEGORIA_HABITO);
CREATE INDEX IX_META_COLAB_HABITO  ON META_SEMANAL (ID_COLABORADOR, ID_HABITO, DT_SEMANA_INICIO);
CREATE INDEX IX_REG_META_DIA       ON REGISTRO_PROGRESSO (ID_META_SEMANAL, DATA_REGISTRO);
CREATE INDEX IX_USUARIO_EMAIL      ON USUARIO (EMAIL);
